#!/bin/sh

brew_cask_is_installed() {
  local NAME=$(brew_cask_expand_alias "$1")
    brew cask list -1 | grep -Fqx "$NAME"
}

brew_cask_install() {
  if ! brew_cask_is_installed "$1"; then
    brew cask install "$@"
  fi
}

brew_cask_install_or_upgrade() {
  if brew_cask_is_installed "$1"; then
    echo "$1 is already installed, brew cask upgrade is not yet implemented"
  else
    brew cask install "$@"
  fi
}

brew tap caskroom/cask
brew update
brew install 'ack'
brew install 'the_silver_searcher'
brew install 'node'
brew install 'thefuck'
brew install 'redis'
brew install 'hub'
brew install 'jmeter'
brew install 'rbenv'
brew install 'pyenv'
brew install 'pyenv-virtualenv'
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

brew install 'vim --override-system-vi'

brew install 'go'
brew install 'elixir'
brew install 'jq'
# Setup Nerves
brew install 'fwup'
brew install 'squashfs'
brew install 'coreutils'
mix local.hex
mix local.rebar
mix archive.install https://github.com/nerves-project/archives/raw/master/nerves_bootstrap.ez

brew install 'mongodb'
# Setup mongodb db folder
sudo mkdir /data/db
sudo chown -R $USER /data/db

brew cask install 'licecap'
brew cask install 'numi'
brew cask install 'kindle'
brew cask install 'send-to-kindle'
brew cask install 'java'
brew cask install 'dropbox'
brew cask install 'google-chrome'
brew cask install 'skitch'
brew cask install 'skype'
brew cask install '1password'
brew cask install 'alfred'
brew cask install 'spectacle'
brew cask install 'google-drive'
brew cask install 'slack'
brew cask install 'iterm2'
brew cask install 'sketch'
brew cask install 'imageoptim'
brew cask install 'garmin-express'
brew cask install 'the-unarchiver'
brew cask install 'filezilla'
brew cask install 'visual-studio-code'
brew cask install 'gitify'
brew cask install 'spotify'

# Phoenix
mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez
# Emacs
brew tap d12frosted/emacs-plus
brew install emacs-plus --with-cocoa --with-gnutls --with-librsvg --with-imagemagick --with-spacemacs-icon
brew linkapps
# Zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
# Git base config
git config --global core.editor "vim"
git config --global user.name "Pierre Lemperiere"
git config --global user.email pierre.lemperiere@gmail.com
# Install Consola font
curl https://gist.githubusercontent.com/Phazz/941c3c1bac48e102ae065a7849a7cdba/raw/f163012bfa836d7db9db9ecf3e08d7f77bb43650/consolas.sh | sh -
# Postgres
echo "============================================================="
echo "You have now to install Postgres from http://postgresapp.com/"
echo "Install also Postico the Postgres client https://eggerapps.at/postico/"
