#!/bin/sh

brew_cask_is_installed() {
  local NAME=$(brew_cask_expand_alias "$1")
    brew cask list -1 | grep -Fqx "$NAME"
}

brew_cask_install() {
  if ! brew_cask_is_installed "$1"; then
    brew cask install "$@"
  fi
}

brew_cask_install_or_upgrade() {
  if brew_cask_is_installed "$1"; then
    echo "$1 is already installed, brew cask upgrade is not yet implemented"
  else
    brew cask install "$@"
  fi
}

brew tap caskroom/cask
brew_install_or_upgrade 'brew-cask'
brew_install_or_upgrade 'thefuck'
brew_install_or_upgrade 'jmeter'
brew_install_or_upgrade 'vim'
brew_cask_install_or_upgrade 'dropbox'
brew_cask_install_or_upgrade 'google-chrome'
brew_cask_install_or_upgrade 'skitch'
brew_cask_install_or_upgrade 'skype'
brew_cask_install_or_upgrade '1password'
brew_cask_install_or_upgrade 'alfred'
brew_cask_install_or_upgrade 'spectacle'
brew_cask_install_or_upgrade 'evernote'
brew_cask_install_or_upgrade 'google-drive'
brew_cask_install_or_upgrade 'deezer'
brew_cask_install_or_upgrade 'atom'
brew_cask_install_or_upgrade 'nylas-n1'
brew_cask_install_or_upgrade 'slack'
brew_cask_install_or_upgrade 'deco'
brew_cask_install_or_upgrade 'iterm2'
apm install sync-settings
