setopt promptsubst

# Load the prompt theme system
autoload -U promptinit
promptinit

# Use the wunjo prompt theme
prompt wunjo
#prompt grb

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Vi default key binding
#bindkey -v
#
#hit Control+V in a shell followed by the key
#for which ou want to get the code

bindkey '^W' backward-kill-word
bindkey '^X*' expand-word
bindkey '^[^H' backward-kill-word
bindkey '^[^_' copy-prev-word
bindkey '^[\$' spell-word
bindkey '^[.' insert-last-word
bindkey '' backward-word
bindkey '^[C' capitalize-word
bindkey '^[D' kill-word
bindkey '' forward-word
bindkey '^[L' down-case-word
bindkey '^[S' spell-word
bindkey '^[T' transpose-words
bindkey '^[U' up-case-word
bindkey '^[_' insert-last-word
bindkey '^[b' backward-word
bindkey '^[c' capitalize-word
bindkey '^[d' kill-word
bindkey '^[f' forward-word
bindkey '^[l' down-case-word
bindkey '^[s' spell-word
bindkey '^[t' transpose-words
bindkey '^[u' up-case-word
bindkey '^[^?' backward-kill-word
# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="sublime ~/.zshrc"
# alias ohmyzsh="sublime ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

# Disable flow control commands (keeps C-s from freezing everything)
stty start undef
stty stop undef

source $ZSH/oh-my-zsh.sh

# Source my custom files after oh-my-zsh so I can override things.
source $HOME/.zsh/aliases
source $HOME/.zsh/functions

# Customize to your needs...
export PATH=/usr/local/bin:$PATH
export PATH=Users/pierre/.rvm/gems/ruby-2.0.0-p247/bin:/Users/pierre/.rvm/gems/ruby-2.0.0-p247@global/bin:/Users/pierre/.rvm/rubies/ruby-2.0.0-p247/bin:/Users/pierre/.rvm/bin:/usr/local/bin:/Users/pierre/.rvm/bin:/usr/local/bin:/Users/pierre/.rvm/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH
export PATH=$PATH:~/bin
### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Postgres config
export PGDATA=/usr/local/var/postgres

# Add data science tools to path
export PATH=$PATH:/Users/pierre/code/dotfiles/command-line-tools-for-data-science/tools

## base16-colors
# Base16 Shell
BASE16_SCHEME="railscasts"
BASE16_SHELL="$HOME/.config/base16-shell/base16-$BASE16_SCHEME.dark.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL

# Go back and forth in the directory tree on zsh startup
# to get tmux using properly .rvmrc file and have rvm properly set
# for the current directory
# 1 is alias of 'cd -'.
cd ..;1

# direnv
eval "$(direnv hook zsh)"

REPORTTIME=3

